scrape_configs:
  - job_name: 'springsmart1'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.19.0.1:8081']
  - job_name: 'springsmart2'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.19.0.1:8082']
  - job_name: 'springsmart3'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.19.0.1:8083']            
